Support `CommandRunner`/`Command`
kevmoo/build_cli pull request #99
Opened 2022-06-08 02:44 UTC by fzyzcjy

Close #29

2022-06-08 03:14 UTC, fzyzcjy commented
ready for review now

2022-06-08 19:57 UTC, kevmoo commented
Need to add this to build_cli/pubspec.yaml

```yaml

dependency_overrides:
  build_cli_annotations:
    path: ../build_cli_annotations
```

2022-06-08 23:27 UTC, fzyzcjy commented
done

2022-06-09 17:41 UTC, kevmoo commented
Yeah, we should have talked more about the output before you created everything.

I was thinking more about having options-within-options.

So if you have a nullable field of a class that annotated with `CliOptions` that would become a command.

Then maybe we do an extension on the class to point to which command is populated or something.

DM me on twitter. Let's set up a meeting and chat about this!

2022-06-09 23:10 UTC, fzyzcjy commented
Sure, I have DM you :)

2022-06-10 04:30 UTC, kevmoo requested changes

2022-06-10 04:30 UTC, kevmoo commented on build_cli_annotations/lib/build_cli_annotations.dart
> +  final bool createCommand;
add a changelog entry and bump the pubspec version to 2.1.0

2022-06-10 04:30 UTC, kevmoo commented on build_cli/pubspec.yaml
> +
Change the `build_cli_annotations` constraint above to `'>=2.1.0 <2.2.0'`

Also change the version of `build_cli` to 2.2.0 – also add a changelog entry

2022-06-10 05:34 UTC, fzyzcjy commented
done

2022-06-10 21:13 UTC, merged

2022-06-10 21:37 UTC, kevmoo commented
FYI: https://github.com/kevmoo/build_cli/pull/101